# Generated by Django 4.2.1 on 2023-06-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mytrainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Faculty', models.CharField(max_length=30)),
            ],
        ),
    ]
