# Generated by Django 4.2.1 on 2023-06-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrainee',
            name='appreciation',
            field=models.CharField(default='good', max_length=12),
            preserve_default=False,
        ),
    ]
